# introduccion a Numpy

[Numpy](https://numpy.org/doc/stable/)  es una biblioteca fundamental para la computacion cientifica con python 
* proporciona arrays N-dimencionales
* implementa funciones sofisticadas
* proporciona herramientas para integrar c/c++ y fortran
* proporciona mecanismos para facilitar la realizaacion de tareas relacionadas con algebra lineal o numeros aleatorios

## imports

In [1]:
import numpy as np

## Arrays

un **array** es una estructura de datos que consiste en una coleccion de elementos (valores o variables), cada uno identificado por almenos un indice o clave. un array se almacena de modo que la posicion de cada elemento se pueda calcular atraves de su tupla de indice mediante una formula matematica. el tipo mas simple es un array lineal, tambien llamado array unidimencional.

en numpy:
* cada dimecion se denomina **axis**.
* el numero de dimenciones se denomina **rank**.
* la lista de dimenciones con su correspondiente longitud se denomina **shape**
* el numero total de elementos que es la multiplicacion de la longitud de las dimenciones se denomina **size**.

In [2]:
# Array cuyos valores son todos 0
a = np.zeros((2,4))

In [3]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

_**a**_ es un array:
* con dos **axis**, el primero de longitud 2 y el segundo de longitud 4.
* con un **rank** igual a 2
* con un **shape** igual (2, 4)
* con un **size** igual a 8

In [4]:
a.shape

(2, 4)

In [5]:
a.ndim

2

In [6]:
a.size

8

## creacion de Arrays

In [7]:
# Array cuyos valores son todos 0
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
# Array cuyos valores son todos 1.
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [9]:
# array cuyos valores son todos el valor indicado como segundo parametro de la funcion
np.full((2, 3, 4), 8)

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [10]:
# el resultado de np. empty no es predecible 
# inicializa los valores del array con lo que haya en la memoria en ese momento
np.empty((2, 3, 9))

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [11]:
# incializacion del array utilizando un array de python
b= np.array([[1, 2, 3,], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b.shape

(2, 3)